import { Vendor } from "@/types/vendor"

export const dummyVendors: Vendor[] = [

  /* =========================
     MAKANAN
  ========================== */

   {
    id: 1,
    name: "Ayam Geprek Kampus",
    slug: "ayam-geprek-kampus",
    category: "makanan",
    photo_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    description: "Danusan ayam geprek murah untuk mahasiswa.",
    address: "Jl. Mawar No.12",
    min_order: "50 pcs",
    price: "Rp 5.000 / pcs",
    whatsapp: "628123456789",
    rating: 4.8,
    distance: "0.8 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
    id: 2,
    name: "Nasi Box Organisasi",
    slug: "nasi-box-organisasi",
    category: "makanan",
    photo_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    description: "Nasi box lengkap untuk acara kampus.",
    address: "Jl. Kenanga No.7",
    min_order: "30 box",
    price: "Rp 18.000 / box",
    whatsapp: "628888111222",
    rating: 4.7,
    distance: "1.2 km",
      discount: true, 
      lat: -7.27,
lng: 112.78,
  },

  {
  id: 3,
  name: "Ayam Bakar Hemat",
  slug: "ayam-bakar-hemat",
  category: "makanan",
  photo_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
  description: "Ayam bakar paket hemat untuk acara.",
  address: "Jl. Mawar No.20",
  min_order: "40 pcs",
  price: "Rp 12.000 / pcs",
  whatsapp: "628111111111",
  rating: 4.6,
  distance: "1 km",
  discount: false,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 4,
  name: "Catering Mahasiswa",
  slug: "catering-mahasiswa",
  category: "makanan",
  photo_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1",
  description: "Catering murah untuk event kampus.",
  address: "Jl. Kenanga No.21",
  min_order: "50 box",
  price: "Rp 15.000 / box",
  whatsapp: "628222222222",
  rating: 4.7,
  distance: "1.5 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 5,
  name: "Ayam Bakar Hemat",
  slug: "ayam-bakar-hemat",
  category: "makanan",
  photo_url: "/ayam6.jpg",
  description: "Ayam bakar paket hemat untuk acara.",
  address: "Jl. Mawar No.20",
  min_order: "40 pcs",
  price: "Rp 12.000 / pcs",
  whatsapp: "628111111111",
  rating: 4.6,
  distance: "1 km",
  discount: false,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 6,
  name: "Dapur Hemat Event",
  slug: "Dapur Hemat Event",
  category: "makanan",
  photo_url: "/ayam.jpg",
  description: "Menyediakan berbagai menu rumahan dengan harga terjangkau, cocok untuk kebutuhan danusan dan acara organisasi kampus.",
  address: "Jl. Mawar No.20",
  min_order: "40 pcs",
  price: "Rp 12.000 / pcs",
  whatsapp: "628265744873",
  rating: 4.7,
  distance: "1.6 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},


{
  id: 7,
  name: "Ayam Geprek Laris",
  slug: "ayam-geprek-laris",
  category: "makanan",
  photo_url: "/ayam2.jpg",
  description: "Ayam geprek crispy dengan sambal pedas favorit mahasiswa, cocok untuk jualan danusan karena murah dan laku keras.",
  address: "Jl. Kenanga No.11",
  min_order: "50 pcs",
  price: "Rp 10.000 / pcs",
  whatsapp: "628123111111",
  rating: 4.8,
  distance: "1 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 8,
  name: "Rice Box Kampus",
  slug: "rice-box-kampus",
  category: "makanan",
  photo_url: "/ayam3.jpg",
  description: "Paket nasi box lengkap dan praktis untuk acara kampus dengan pilihan lauk variatif.",
  address: "Jl. Melati No.9",
  min_order: "30 box",
  price: "Rp 15.000 / box",
  whatsapp: "628123222222",
  rating: 4.6,
  distance: "1.4 km",
  discount: false,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 9,
  name: "Warung Nasi Mahasiswa",
  slug: "warung-nasi-mahasiswa",
  category: "makanan",
  photo_url: "/ayam4.jpg",
  description: "Warung nasi dengan harga ramah mahasiswa, cocok untuk konsumsi acara maupun dijual kembali.",
  address: "Jl. Dahlia No.6",
  min_order: "40 pcs",
  price: "Rp 12.000 / pcs",
  whatsapp: "628123333333",
  rating: 4.7,
  distance: "0.9 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 10,
  name: "Catering Anak Kampus",
  slug: "catering-anak-kampus",
  category: "makanan",
  photo_url: "/ayam5.jpg",
  description: "Layanan catering khusus event kampus dengan menu sederhana, enak, dan harga terjangkau.",
  address: "Jl. Flamboyan No.10",
  min_order: "50 box",
  price: "Rp 17.000 / box",
  whatsapp: "628123444444",
  rating: 4.9,
  distance: "2 km",
  discount: false,
  lat: -7.27,
  lng: 112.78,
},
  /* =========================
     MINUMAN
  ========================== */

  {
    id: 11,
    name: "Es Teh Jumbo",
    slug: "es-teh-jumbo",
    category: "minuman",
    photo_url: "https://images.unsplash.com/photo-1497534446932-c925b458314e",
    description: "Minuman segar untuk event kampus.",
    address: "Jl. Melati No.10",
    min_order: "30 pcs",
    price: "Rp 3.000 / pcs",
    whatsapp: "628987654321",
    rating: 4.7,
    distance: "1 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
    id: 12,
    name: "Booth Kopi Mahasiswa",
    slug: "booth-kopi-mahasiswa",
    category: "minuman",
    photo_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
    description: "Booth kopi untuk event kampus.",
    address: "Jl. Dahlia No.2",
    min_order: "1 booth",
    price: "Mulai Rp 1.200.000",
    whatsapp: "628777222333",
    rating: 4.9,
    distance: "2 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },


  {
  id: 13,
  name: "Es Teh Ramean Kampus",
  slug: "es-teh-ramean-kampus",
  category: "minuman",
  photo_url: "/esteh.jpg",
  description: "Es teh jumbo segar cocok untuk jualan danusan dengan harga super ramah mahasiswa.",
  address: "Jl. Kenanga No.3",
  min_order: "30 pcs",
  price: "Rp 3.000 / pcs",
  whatsapp: "628123450001",
  rating: 4.6,
  distance: "1 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 14,
  name: "Booth Jus Segar Mahasiswa",
  slug: "booth-jus-segar-mahasiswa",
  category: "minuman",
  photo_url: "/jus.jpg",
  description: "Aneka jus buah segar dengan konsep booth untuk meramaikan event kampus.",
  address: "Jl. Melati No.8",
  min_order: "1 booth",
  price: "Mulai Rp 900.000",
  whatsapp: "628123450002",
  rating: 4.8,
  distance: "1.5 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 15,
  name: "Minuman Kekinian Kampus",
  slug: "minuman-kekinian-kampus",
  category: "minuman",
  photo_url: "/boba.jpg",
  description: "Thai tea, boba, dan minuman hits lainnya cocok untuk jualan anak kampus.",
  address: "Jl. Dahlia No.5",
  min_order: "25 pcs",
  price: "Rp 8.000 / pcs",
  whatsapp: "628123450003",
  rating: 4.7,
  distance: "2 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 16,
  name: "Kopi Literan Event",
  slug: "kopi-literan-event",
  category: "minuman",
  photo_url: "/kopi.jpg",
  description: "Kopi literan hemat untuk panitia dan peserta acara kampus.",
  address: "Jl. Anggrek No.4",
  min_order: "10 liter",
  price: "Rp 85.000 / liter",
  whatsapp: "628123450004",
  rating: 4.9,
  distance: "2.5 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 17,
  name: "Es Buah Segar Danusan",
  slug: "es-buah-segar-danusan",
  category: "minuman",
  photo_url: "/esbuah.jpg",
  description: "Es buah segar dengan topping lengkap, cocok untuk jualan panas-panasan di kampus.",
  address: "Jl. Flamboyan No.6",
  min_order: "20 pcs",
  price: "Rp 6.000 / pcs",
  whatsapp: "628123450005",
  rating: 4.7,
  distance: "1.8 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},
  /* =========================
     SNACK
  ========================== */

  {
    id: 18,
    name: "Snack Box Hemat",
    slug: "snack-box-hemat",
    category: "snack",
    photo_url: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092",
    description: "Snack box murah untuk acara organisasi.",
    address: "Jl. Kenanga No.5",
    min_order: "20 box",
    price: "Rp 10.000 / box",
    whatsapp: "6281122334455",
    rating: 4.9,
    distance: "0.5 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
    id: 19,
    name: "Dessert Box Lumer",
    slug: "dessert-box-lumer",
    category: "snack",
    photo_url: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    description: "Dessert box premium untuk danusan.",
    address: "Jl. Flamboyan No.3",
    min_order: "25 box",
    price: "Rp 15.000 / box",
    whatsapp: "6282211003344",
    rating: 4.8,
    distance: "1.5 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
  id: 20,
  name: "Cemilan Goreng Kampus",
  slug: "cemilan-goreng-kampus",
  category: "snack",
  photo_url: "/gorengan.jpg",
  description: "Aneka gorengan seperti risol, pastel, dan tahu isi yang cocok untuk jualan danusan harian.",
  address: "Jl. Melati No.2",
  min_order: "50 pcs",
  price: "Rp 2.000 / pcs",
  whatsapp: "628123450010",
  rating: 4.7,
  distance: "0.7 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 21,
  name: "Roti Bakar Mini Kekinian",
  slug: "roti-bakar-mini-kekinian",
  category: "snack",
  photo_url: "/rotibakar.jpg",
  description: "Roti bakar mini dengan topping coklat, keju, dan matcha, cocok untuk jualan anak kampus.",
  address: "Jl. Dahlia No.7",
  min_order: "30 pcs",
  price: "Rp 5.000 / pcs",
  whatsapp: "628123450011",
  rating: 4.8,
  distance: "1 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 22,
  name: "Donat Kentang Empuk",
  slug: "donat-kentang-empuk",
  category: "snack",
  photo_url: "/donat.jpg",
  description: "Donat kentang empuk dengan berbagai topping manis, cocok untuk danusan dan event kampus.",
  address: "Jl. Anggrek No.10",
  min_order: "40 pcs",
  price: "Rp 3.500 / pcs",
  whatsapp: "628123450012",
  rating: 4.9,
  distance: "1.2 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 23,
  name: "Cireng Isi Frozen",
  slug: "cireng-isi-frozen",
  category: "snack",
  photo_url: "/cireng.jpg",
  description: "Cireng isi ayam dan keju, bisa dijual goreng langsung atau dalam bentuk frozen.",
  address: "Jl. Cempaka No.4",
  min_order: "50 pcs",
  price: "Rp 2.500 / pcs",
  whatsapp: "628123450013",
  rating: 4.7,
  distance: "1.4 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 24,
  name: "Piscok Lumer Kampus",
  slug: "piscok-lumer-kampus",
  category: "snack",
  photo_url: "/piscok.jpg",
  description: "Pisang coklat lumer favorit mahasiswa, cocok untuk jualan cepat laku di area kampus.",
  address: "Jl. Flamboyan No.9",
  min_order: "40 pcs",
  price: "Rp 3.000 / pcs",
  whatsapp: "628123450014",
  rating: 4.8,
  distance: "0.9 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},
  /* =========================
     MERCHANDISE
  ========================== */

  {
    id: 20,
    name: "Kaos Event Custom",
    slug: "kaos-event-custom",
    category: "merchandise",
    photo_url: "/kaos2.jpg",
    description: "Custom tote bag untuk event kampus.",
    address: "Jl. Cempaka No.1",
    min_order: "50 pcs",
    price: "Rp 20.000 / pcs",
    whatsapp: "6283344556677",
    rating: 4.7,
    distance: "3 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
  id: 22,
  name: "Hoodie Custom Kampus",
  slug: "hoodie-custom-kampus",
  category: "merchandise",
  photo_url: "/hoodie.jpg",
  description: "Custom hoodie keren untuk panitia dan komunitas kampus.",
  address: "Jl. Melati No.11",
  min_order: "24 pcs",
  price: "Rp 95.000 / pcs",
  whatsapp: "628123450020",
  rating: 4.8,
  distance: "2.5 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 23,
  name: "Lanyard & ID Card Event",
  slug: "lanyard-id-card-event",
  category: "merchandise",
  photo_url: "/lanyard.jpg",
  description: "Cetak lanyard dan ID card untuk panitia, seminar, dan event kampus.",
  address: "Jl. Kenanga No.9",
  min_order: "50 pcs",
  price: "Rp 8.000 / pcs",
  whatsapp: "628123450021",
  rating: 4.7,
  distance: "1.8 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 24,
  name: "Sticker & Stiker Branding",
  slug: "sticker-branding-kampus",
  category: "merchandise",
  photo_url: "/sticker.jpg",
  description: "Cetak sticker logo organisasi untuk promosi dan branding event.",
  address: "Jl. Dahlia No.6",
  min_order: "100 pcs",
  price: "Rp 1.000 / pcs",
  whatsapp: "628123450022",
  rating: 4.6,
  distance: "1.2 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 25,
  name: "Topi Custom Event",
  slug: "topi-custom-event",
  category: "merchandise",
  photo_url: "/topi.jpg",
  description: "Topi custom untuk panitia dan merchandise event kampus.",
  address: "Jl. Flamboyan No.12",
  min_order: "30 pcs",
  price: "Rp 35.000 / pcs",
  whatsapp: "628123450023",
  rating: 4.7,
  distance: "2 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 26,
  name: "Goodie Bag Seminar Kit",
  slug: "goodie-bag-seminar-kit",
  category: "merchandise",
  photo_url: "/goodiebag.jpg",
  description: "Paket goodie bag lengkap untuk seminar, workshop, dan event kampus.",
  address: "Jl. Mawar No.18",
  min_order: "50 pcs",
  price: "Rp 25.000 / pcs",
  whatsapp: "628123450024",
  rating: 4.8,
  distance: "2.3 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},
  /* =========================
     DOKUMENTASI
  ========================== */

  {
    id: 27,
    name: "Fotografer Kampus Pro",
    slug: "fotografer-kampus-pro",
    category: "dokumentasi",
    photo_url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32",
    description: "Jasa dokumentasi event dan aftermovie.",
    address: "Jl. Anggrek No.2",
    min_order: "1 event",
    price: "Mulai Rp 750.000",
    whatsapp: "6285566778899",
    rating: 4.9,
    distance: "3 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
    id: 28,
    name: "Videografer Aftermovie",
    slug: "videografer-aftermovie",
    category: "dokumentasi",
    photo_url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    description: "Paket video cinematic untuk acara kampus.",
    address: "Jl. Melati No.9",
    min_order: "1 event",
    price: "Mulai Rp 1.200.000",
    whatsapp: "6289988776655",
    rating: 4.8,
    distance: "4 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
  id: 29,
  name: "Tim Foto Wisuda Kampus",
  slug: "tim-foto-wisuda-kampus",
  category: "dokumentasi",
  photo_url: "/wisuda.jpg",
  description: "Jasa foto wisuda dan dokumentasi acara formal kampus dengan hasil profesional.",
  address: "Jl. Kenanga No.11",
  min_order: "1 event",
  price: "Mulai Rp 500.000",
  whatsapp: "628123450030",
  rating: 4.8,
  distance: "2.5 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 30,
  name: "Aftermovie Cinematic Crew",
  slug: "aftermovie-cinematic-crew",
  category: "dokumentasi",
  photo_url: "/cinematic.jpg",
  description: "Tim videografer untuk pembuatan aftermovie cinematic event kampus.",
  address: "Jl. Dahlia No.12",
  min_order: "1 event",
  price: "Mulai Rp 1.500.000",
  whatsapp: "628123450031",
  rating: 4.9,
  distance: "3.2 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 31,
  name: "Live Streaming Event Kampus",
  slug: "live-streaming-event-kampus",
  category: "dokumentasi",
  photo_url: "/streaming.jpg",
  description: "Layanan live streaming untuk seminar, webinar, dan event kampus.",
  address: "Jl. Anggrek No.6",
  min_order: "1 event",
  price: "Mulai Rp 800.000",
  whatsapp: "628123450032",
  rating: 4.7,
  distance: "2.8 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 32,
  name: "Photobooth Event Seru",
  slug: "photobooth-event-seru",
  category: "dokumentasi",
  photo_url: "/photobooth.jpg",
  description: "Photobooth kekinian untuk meramaikan event dan menarik pengunjung.",
  address: "Jl. Flamboyan No.10",
  min_order: "1 paket",
  price: "Mulai Rp 700.000",
  whatsapp: "628123450033",
  rating: 4.8,
  distance: "3 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 33,
  name: "Drone Video Event",
  slug: "drone-video-event",
  category: "dokumentasi",
  photo_url: "/drone.jpg",
  description: "Pengambilan video aerial menggunakan drone untuk event kampus.",
  address: "Jl. Mawar No.22",
  min_order: "1 event",
  price: "Mulai Rp 1.000.000",
  whatsapp: "628123450034",
  rating: 4.9,
  distance: "3.5 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},
  /* =========================
     PERLENGKAPAN
  ========================== */

  {
    id: 11,
    name: "Sewa Tenda & Sound",
    slug: "sewa-tenda-sound",
    category: "perlengkapan",
    photo_url: "https://images.unsplash.com/photo-1506157786151-b8491531f063",
    description: "Sewa tenda, sound system, dan lighting.",
    address: "Jl. Flamboyan No.8",
    min_order: "1 paket",
    price: "Mulai Rp 1.500.000",
    whatsapp: "6284455667788",
    rating: 4.8,
    distance: "4 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
    id: 12,
    name: "Lighting & Stage Setup",
    slug: "lighting-stage-setup",
    category: "perlengkapan",
    photo_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745",
    description: "Paket panggung dan lighting event.",
    address: "Jl. Mawar No.15",
    min_order: "1 paket",
    price: "Mulai Rp 2.000.000",
    whatsapp: "6287766554433",
    rating: 4.9,
    distance: "5 km",
     discount: true, 
     lat: -7.27,
lng: 112.78,
  },

  {
  id: 13,
  name: "Sewa Kursi & Meja Event",
  slug: "sewa-kursi-meja-event",
  category: "perlengkapan",
  photo_url: "/kursi.jpg",
  description: "Penyewaan kursi dan meja untuk seminar, lomba, dan acara kampus.",
  address: "Jl. Kenanga No.14",
  min_order: "50 pcs",
  price: "Rp 3.000 / pcs",
  whatsapp: "628123450040",
  rating: 4.7,
  distance: "3 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 14,
  name: "Sewa Sound System Pro",
  slug: "sewa-sound-system-pro",
  category: "perlengkapan",
  photo_url: "/sound.jpg",
  description: "Sound system lengkap untuk acara indoor maupun outdoor.",
  address: "Jl. Dahlia No.13",
  min_order: "1 paket",
  price: "Mulai Rp 800.000",
  whatsapp: "628123450041",
  rating: 4.8,
  distance: "3.5 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 15,
  name: "Backdrop & Banner Event",
  slug: "backdrop-banner-event",
  category: "perlengkapan",
  photo_url: "/backdrop.jpg",
  description: "Cetak backdrop, banner, dan dekorasi visual untuk event kampus.",
  address: "Jl. Anggrek No.9",
  min_order: "1 paket",
  price: "Mulai Rp 500.000",
  whatsapp: "628123450042",
  rating: 4.6,
  distance: "2.7 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 16,
  name: "Sewa Panggung Portable",
  slug: "sewa-panggung-portable",
  category: "perlengkapan",
  photo_url: "/panggung.jpg",
  description: "Panggung portable untuk acara kampus skala kecil hingga besar.",
  address: "Jl. Flamboyan No.15",
  min_order: "1 paket",
  price: "Mulai Rp 1.200.000",
  whatsapp: "628123450043",
  rating: 4.8,
  distance: "4.2 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},

{
  id: 17,
  name: "Genset & Listrik Event",
  slug: "genset-listrik-event",
  category: "perlengkapan",
  photo_url: "/apalah.jpg",
  description: "Sewa genset untuk mendukung kebutuhan listrik acara kampus.",
  address: "Jl. Mawar No.25",
  min_order: "1 unit",
  price: "Mulai Rp 900.000",
  whatsapp: "628123450044",
  rating: 4.7,
  distance: "4.5 km",
  discount: true,
  lat: -7.27,
  lng: 112.78,
},
]


